# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Subjects(models.Model):
	Categories = models.CharField(max_length=200)
	Subject = models.CharField(max_length=200)
	
#id/primary key is autogenerated
class Treeinfo(models.Model):
	Name = models.CharField(max_length=200)
	Category = models.CharField(max_length=200)
	Subject = models.CharField(max_length=200)
	#add whatever we need fir dir
	
